### ISSUE TITLE
some question on travis-ci

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-cjson#11]
hello,

what should find 

```
grep -E '^==[0-9]+==' build.log; if [ "$?" == 0 ]; then exit 1; else exit 0; fi
```

it seems does not catch failed tests:

https://travis-ci.org/openresty/lua-cjson/jobs/165900574#L583

**Comment by agentzh** [comment]
It's for catching valgrind errors.

**Comment by chipitsine** [comment]
I seem to have that fixed in https://github.com/openresty/lua-cjson/pull/13
