### ISSUE TITLE
empty_array behavior

### ISSUE THREAD

**Issue by cubicdaiya** [openresty/lua-cjson#15]
Hi,

It seems the behavior of **empty_array** is different from [document](https://github.com/openresty/lua-cjson#empty_array).

```lua
local cjson = require "cjson"

local json = cjson.encode({
    foo = "bar",
    some_object = {},
    some_array = cjson.empty_array
})
```

It indicates that the code above generates the body below in document.

```json
{
    "foo": "bar",
    "some_object": {},
    "some_array": []
}
```

But the generated body in actual is below.

```json
{
  "some_object": {},
  "foo": "bar"
}
```

Is this a bug?

**Comment by moonbingbing** [comment]
location / {
            content_by_lua_block {
            local cjson = require "cjson"
            local json = cjson.encode({
            foo = "bar",
            some_object = {},
            some_array = cjson.empty_array
            })
            ngx.say(json)
            }
        }

the output include "some_array":[].  my OpenResty version is 1.11.2.1.

can you give one example about the problem?

2016-12-12 11:47 GMT+08:00 Tatsuhiko Kubo <notifications@github.com>:

**Comment by cubicdaiya** [comment]
@moonbingbing Thank you for the reply and sorry. I noticed the cause. It is the below.

```
lua_package_cpath '/etc/nginx/lualib/?.so;;';
```

There were very old **cjson.so** in the directory above. The cause is my environment. Sorry again...
