### ISSUE TITLE
more clever decode() needed

### ISSUE THREAD

**Issue by dklunarian** [openresty/lua-cjson#25]
`local cjson = require("cjson")

local json = [[{"empty_array":[],"empty_object":{}}]]
ngx.say(cjson.encode(cjson.decode(json)))`

above output:
> {"empty_array":{},"empty_object":{}}

should output:
> {"empty_array":[],"empty_object":{}}

if in lua_cjson.c could cleverly setmetatable of empty array to **empty_array_mt** in decode process

**Comment by taskoma** [comment]
without it schema modified and can't use library

**Comment by thibaultcha** [comment]
Such a feature is on the roadmap for this module, I am planning a contribution for it but feel free to submit your own!

**Comment by thibaultcha** [comment]
I have just opened openresty/lua-cjson#28, reviews appreciated!

**Comment by Tieske** [comment]
since #28 was merged and released, this can be closed now.
