### ISSUE TITLE
possible to get this version in luarocks?

### ISSUE THREAD

**Issue by 2m4qhki3** [openresty/lua-cjson#29]
The rocks file is already in the repository so it's simple enough to `git clone` and then `luarocks make lua-cjson-2.1devel-1.rockspec`

Still, if this version was added to luarocks it would simpler and more convenient to install.

**Comment by FourierTransformer** [comment]
Yeah, is there any chance of this getting into LuaRocks? It's the most downloaded module on LuaRocks and is now broken in the latest LuaJIT and the openresty fork is the best version currently out there.

**Comment by agentzh** [comment]
@FourierTransformer I don't think we can upload a new LuaRocks library with the same name given the flat namespace in LuaRocks's module index.

**Comment by FourierTransformer** [comment]
I wonder if @hishamhm can offer some guidance on what should be done.

**Comment by thibaultcha** [comment]
There is already a rock for this fork on LuaRocks: https://luarocks.org/modules/criztianix/lua-cjson2 

I haven’t tested it myself though.

**Comment by FourierTransformer** [comment]
I think it would preferable if it wasn't maintained separately (one more person who'd need to keep up with updates and so on)...

**Comment by 2m4qhki3** [comment]
I agree with Fourier. There's also the issue of trusting a third-party to not tamper with the code.

**Comment by hishamhm** [comment]
The lua-cjson rock is currently unclaimed in luarocks.org (i.e. it is assigned to the umbrella `luarocks` account which was created when we migrated the repo to the (then) new LuaRocks infrastructure.)

The original lua-cjson also seems unmaintained. Is this fork backwards compatible? If so, it would make sense for it to take over the `lua-cjson` entry in the root manifest of luarocks.org.

The command-line tool uses the root manifest by default, but each user account gets its own manifest in the luarocks.org server, so it is possible to upload a package with the same name and it will show up in the user's own namespace (and in the root namespace if they are assigned the slot; `lua-cjson` is unclaimed). Support for fetching namespace-specific dependencies is coming in the next release. But in this case it sounds like this rock should be in the root manifest anyway! (I can transfer the `lua-cjson` slot in the root manifest from the `luarocks` account to one maintained by this org.)

**Comment by agentzh** [comment]
@hishamhm Yes, we try hard to maintain backward compatibility. Thanks for your help and we'd love to get the lua-cjson slot on luarocks. Please let us know how to proceed. @moonming in our openresty org can take this over. His email address is wenming@openresty.org. Thanks!

**Comment by hishamhm** [comment]
@agentzh cool! I emailed @moonming with all the details.

**Comment by 2m4qhki3** [comment]
Nice job yall! Looks like you have control of the repository now: https://luarocks.org/modules/openresty/lua-cjson

Looks like the latest openresty version is 2.1.0.6rc2, but luarocks has version 2.1.0.1.

**Comment by agentzh** [comment]
@2m4qhki3 We'll wait for the next formal release tag, 2.1.0.6.

**Comment by kazuhiro** [comment]
Is there a known date for 2.1.0.6 release and a final solution of this issue? :)

**Comment by ivaaaan** [comment]
Any updates? How to install this version of lua-json to OpenResty?

**Comment by agentzh** [comment]
@kazuhiro 2.1.0.6 is already tagged and @moonming is taking care of the luarocks part I believe.

**Comment by moonming** [comment]
@kazuhiro 2.1.0.6 is already uploaded to luarocks: http://luarocks.org/modules/openresty/lua-cjson/2.1.0.6-1. please have a try, thanks.

**Comment by kazuhiro** [comment]
thanks! :)
