### ISSUE TITLE
How decode json object or array with empty?

### ISSUE THREAD

**Issue by wuyachao** [openresty/lua-cjson#34]
When I  proxy json body with object and array. Update it and proxy to backend.   origin is ：
```
{"name":"wyc","info":{},"list":[]}
```
After update this json,  the  json will ：
```
{
"list": {},
"info": {},
"name": "wyc"
}
```
When use `cjson.encode_empty_table_as_object(false)`. it still not correct.  the dkjson can do it correctly.How can i do it.

**Comment by agentzh** [comment]
@wuyachao Seems like you are confused with "encode" with "decode"? You are decoding a JSON here but you set an option for JSON encoding. I'm not sure what you are really trying to do here.

**Comment by wuyachao** [comment]
1.origin is ：
```
{"name":"wyc","info":{},"list":[]}
```
2.add age = 111
```
local aa = [[{"name":"wyc","info":{},"list":[]}]]
local bb = cjson.decode(aa)
bb.age = 111
ngx.say(cjson.encode(bb))
```
3. the result is ：
```
{
"list": {},
"info": {},
"age": 111,
"name": "wyc"
}
```
the list and info is also empty object.  But `list` is an array，`info` is empty object.

`cjson.decode_array_with_array_mt(true)`  can do it.  I will close this issue.

**Comment by wuyachao** [comment]
@agentzh  this is same to  https://github.com/openresty/lua-cjson/issues/33
