### ISSUE TITLE
undefined symbol: luaL_setfuncs

### ISSUE THREAD

**Issue by ilham9649** [openresty/lua-cjson#37]
Hi, after build the the library to cjson.so, i load the module but unfortunately there's this error : 
ccess_by_lua(nginx.conf:144):3: in function <access_by_lua(nginx.conf:144):1>, client: 10.193.251.185, server: internalproxy.cwpinfra, request: "GET /index.html HTTP/1.1", host: "10.193.6.247"
2018/02/21 18:21:07 [error] 6828#6828: *25 lua entry thread aborted: runtime error: error loading module 'resty.cjson' from file '/etc/nginx/modules/lua-resty/lib/resty/cjson.so':
        /etc/nginx/modules/lua-resty/lib/resty/cjson.so: undefined symbol: luaL_setfuncs
stack traceback:
coroutine 0:
Is it some issue or there is something wrong when i build the library? Thanks

**Comment by agentzh** [comment]
@ilham9649 I don't think 'resty.cjson` is our Lua module name. Seems like you copied the cjson file to the wrong place.

Also, you seem to compile the cjson library using the wrong version of Lua header files.

To avoid such troubles, please just use the OpenResty releases (there are also many other ways to get things wrong):

https://openresty.org/en/download.html
