### ISSUE TITLE
Why “/” will be escaped

### ISSUE THREAD

**Issue by imilli** [openresty/lua-cjson#45]
exp:
local t = {"ban/ana"}
local res = cjson.encode(t)
ngx.say(res)

the result is {"ban\\/ana"}

But others json lib will not do this, exp jsoncpp.
If i have to do this, is there any way to avoid it?

another issue:
I want to modify string {"ban\\/ana"} to {"ban/ana"} with ngx.re.gsub(res, "\\/", "/", "jo")
but result is  {"ban\\/ana"} still.

**Comment by thibaultcha** [comment]
This has been answered in the issue you opened in the upstream version of this repository (https://github.com/mpx/lua-cjson/issues/62). I am thus closing this, since the answer there is correct.

Thanks
