### ISSUE TITLE
CJSON version 2.1.0.7 reports 2.1.0.6

### ISSUE THREAD

**Issue by pdomings1** [openresty/lua-cjson#48]
In lua_cjson.c , CJSON_VERSION is defined as  2.1.0.6 instead 2.1.07 causing print of cjson._VERSION in lua to shows the wrong version.

**Comment by blueowl04** [comment]
The same is true for 2.1.0.8  release. It still contains `#define CJSON_VERSION   "2.1.0.6"`

**Comment by leafo** [comment]
The most recent version have the version string set correctly. I don't think anyone is going to go back and re-release the older versions, so I recommend sticking with the most recent version to avoid any issues with incorrect version string within the library.
