### ISSUE TITLE
cygwin中使用openresty自带的cjson异常

### ISSUE THREAD

**Issue by jordon1899** [openresty/lua-cjson#52]
![image](https://user-images.githubusercontent.com/32090776/67538716-88511d00-f712-11e9-9cb7-05c176fbb274.png)
$ luajit
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> local a = require ('cjson');
error loading module 'cjson' from file '/usr/local/lib/lua/5.1/cjson.so':
        No such process
stack traceback:
        [C]: at 0x63b586b0
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: at 0x00401df0

lua_cjson使用以下命令编译和链接：
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/usr/local/include/luajit-2.1/ -fpic -o lua_cjson.o lua_cjson.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/usr/local/include/luajit-2.1/ -fpic -o strbuf.o strbuf.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/usr/local/include/luajit-2.1/ -fpic -o fpconv.o fpconv.c
cc  -L../luajit-root/usr/local/openresty/luajit -lcyglua51 -o cjson.so lua_cjson.o strbuf.o fpconv.o
cygwin是32位的,luajit也是openresty自带的

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding your question, Cygwin is not an officially supported target. You can try our official Windows binary package built by the MinGW2 toolchain:

http://openresty.org/en/download.html#windows

**Comment by jordon1899** [comment]
I resolved this problem by :
cc -L../luajit-root/usr/local/openresty/luajit -lcyglua51 -o cjson.so lua_cjson.o strbuf.o fpconv.o
replace:
cc -L../luajit-root/usr/local/openresty/luajit -lcyglua51 -shared  -o cjson.so lua_cjson.o strbuf.o fpconv.o

I alrealy deploy lastly version openresty-1.15.8.2.tar.gz、lor-0.3.4.tar.gz、organge-0.8.0.tar.gz on cygwin( CYGWIN_NT-6.1-WOW mePC 3.0.7(0.338/5/3) 2019-04-30 18:04 i686 Cygwin） and run fine.
