### ISSUE TITLE
The question about decoding number and boolean when using cjson

### ISSUE THREAD

**Issue by kakascx** [openresty/lua-cjson#53]
I found  a phenomenon that when the text is a number,the decode function passes the text transparently. For example,
```
local cjson = require"cjson.safe"
local num = 9
local res = cjson.decode(num)
print(res)   -- the decode resulte is 9 

```
Is this meet the json specification? In this way, will the decode funtion pass the text in boolean transparently either?

**Comment by leafo** [comment]
The Lua C API for processing arguments can coerce some types automatically. In this case a number is converted to a string before being processed by decode: https://pgl.yoyo.org/luai/i/lua_tolstring
