### ISSUE TITLE
Support encoding/decoding with 0-based tables

### ISSUE THREAD

**Issue by jdonaldson** [openresty/lua-cjson#65]
I work with a language that targets lua: https://haxe.org/blog/hello-lua/

It's often necessary to encode/decode json using 0-indexed tables.  Would it be appropriate to add an option for this to the library here?  As a side note, I think it should be some sort of option passed to a decode/encode method, and not something that relies on metatables or some sort of static initialization.

**Comment by leafo** [comment]
I do not think it would be an appropriate change to this library, as Lua is a 1 indexed language. In order to avoid polluting the API with edge cases, I think simple transformations should be handled in Lua before interacting with `encode` and `decode`.

**Comment by jdonaldson** [comment]
Maybe I'm not thinking deeply enough, but my understanding was that if the table is deserialized as 1-indexed, it is cost prohibitive to re-index as 0-based.  Is there some mechanism we can take advantage of here?  Or is the only way forward to roll our own suite of encoding/decoding libraries?
