### ISSUE TITLE
empty_array can not work on Apple M1 + VMware fusion Tech preview + ubuntu 22.04

### ISSUE THREAD

**Issue by chronolaw** [openresty/lua-cjson#81]
Hi,

Now I am using Macbook Pro with M1 Max, I installed VMware fusion Tech preview to support M1 Virtualization, and setup the latest ubuntu 22.04 arm version for development.

I found a strange bug: cjson.empty_array can  not work as expect, when I call cjson.encode, it output nothing. but I use another Macbook with intel CPU, it works well.

I also tried docker image openresty/openresty:alpine, and get the same result.

Could someone tell me what shall I do or workaround?

The OpenResty version is 1.19.9.1, Here is my Lua code:

~~~
local cjson=require"cjson"

os.execute("cat /etc/os-release")
os.execute("uname -a")
os.execute("gcc --version")

print(ngx.config.nginx_version)
print(ngx.config.ngx_lua_version)
print(cjson._VERSION)

local data = { a=cjson.empty_array }

print(cjson.encode(data))
print(cjson.empty_array)

cjson.encode_empty_table_as_object(false)
print(cjson.encode({a={}}))
~~~

the result is :

~~~
PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
Linux myresty 5.13.0-19-generic #19-Ubuntu SMP Thu Oct 7 17:48:36 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
gcc (Ubuntu 11.2.0-13ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

1019009
10020
2.1.0.6
{"a":}
userdata: 0x7fff893fcb68
{"a":[]}
~~~

The config file for openresty image is:

~~~
server {
    listen 80;
    location / {
        content_by_lua_block {
            local cjson=require"cjson"
            --ngx.say("hello cjson")
            ngx.say(cjson._VERSION)

            local data = { a=cjson.empty_array }
            ngx.say(cjson.encode(data))
        }
    }
}
~~~

Then run the image:
~~~
docker run -it -d -v `pwd`/default.conf:/etc/nginx/conf.d/default.conf -p 80:80 openresty/openresty:alpine
curl 127.1
2.1.0.6
{"a":}
~~~

**Comment by chronolaw** [comment]
I try gdb cjson.so, get some result.

in json_encode() => json_append_data(), line 799,
It will compare with the address of `json_array`,
but they are different, so it fall though.

Here is the gdb info:
~~~
Value returned is $14 = (void *) 0x7ffff7753b68
(gdb) p &json_array
$15 = (const char * const **) 0xfffff7753b68
~~~

Can we change the `json_lightudata_mask` shift from `47` to `48`?

**Comment by chronolaw** [comment]
After I change the number  `47` to `48` in json_lightudata_mask, It works well on my VM.

If you think it is good, I am glad to commit this patch.

**Comment by dndx** [comment]
@chronolaw Could you test if #82 fixes the issue? It seems to be a negligence when doing comparisons for lightuserdata address.

**Comment by bungle** [comment]
Seems like duplicate to: https://github.com/openresty/lua-cjson/issues/61
