### ISSUE TITLE
+bug,Construct a special character handling bug for JSON data objects

### ISSUE THREAD

**Issue by CLX102030** [openresty/lua-cjson#97]
Hello author, in the construction of the json data object as a url such as: http://www.baidu.com, the output result is: http:\/\/www.baidu.com,
dbug:  After checking, it was found that it was a problem with the special character handling table.

solution: 
<img width="383" alt="image" src="https://github.com/openresty/lua-cjson/assets/90083278/a98782b7-4310-4ddb-a289-e367855d13f4">

**Comment by CLX102030** [comment]
the output result is: http:\/\/www.baidu.com,

**Comment by CLX102030** [comment]
\\/\\/

**Comment by CLX102030** [comment]
<img width="154" alt="image" src="https://github.com/openresty/lua-cjson/assets/90083278/baec8df4-6eac-4ea3-8592-c52d4dd04a6d">

**Comment by CLX102030** [comment]
The first commit ignores that GitHub automatically handles special characters

**Comment by zhuizhuhaomeng** [comment]
According to https://www.json.org/json-en.html, we need to escape slash.

**Comment by CLX102030** [comment]
正常的传入的参数url是http://www.baidu.com，但是转换为字符串后多出一个\\这样总不大对吧

**Comment by CLX102030** [comment]
输出结果为http:\\/\\/www.baidu.com，这样会多出来的一个字符不太正确吧

**Comment by CLX102030** [comment]
The normal incoming parameter url is http://www.baidu.com,
but After conversion is http:\\/\\/www.baidu.com,There is a difference with the result

**Comment by zhuizhuhaomeng** [comment]
You can try it at https://nddapp.com/json-encoder.html.
As I mentioned before, you should read the json standard in https://www.json.org/json-en.html.

**Comment by CLX102030** [comment]
好的，谢谢
